<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MM5QJ97" name="tests.Admin_Login_Test" tests="1" failures="1" timestamp="5 Apr 2022 08:57:48 GMT" time="43.430" errors="0">
  <testcase name="login_eCollabDDS_Admin" time="43.430" classname="tests.Admin_Login_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Fail: Login_with_valid_username_password expected [https://cors.ehospital.nic.in/rad/management/show] but found [https://cors.ehospital.nic.in/rad/management/login?error]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Fail: Login_with_valid_username_password expected [https://cors.ehospital.nic.in/rad/management/show] but found [https://cors.ehospital.nic.in/rad/management/login?error]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at tests.Admin_Login_Test.login_eCollabDDS_Admin(Admin_Login_Test.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- login_eCollabDDS_Admin -->
</testsuite> <!-- tests.Admin_Login_Test -->
